steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', 'gcr.io/sample/my-sample-webapp', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/sample/my-sample-webapp', ]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'my-sample-webapp'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--image=gcr.io/sample/my-sample-webapp'
    
